### ISSUE TITLE
Problem with iOS building

### ISSUE THREAD

**Issue by gojkokbc** [owncloud/ios#614]
Hi i have following errors when build in Xcode 7.3:
/Users/gojkob/ios/OC Share Sheet/ShareViewController.swift:210:42: error: use of unresolved identifier 'enumKindOfError'
                    upload.kindOfError = enumKindOfError.notAnError.rawValue
                                         ^~~~~~~~~~~~~~~
/Users/gojkob/ios/OC Share Sheet/ShareViewController.swift:213:37: error: use of unresolved identifier 'enumUpload'
                    upload.status = enumUpload.generatedByDocumentProvider.rawValue

**Comment by javiergonzper** [comment]
Looks like there are changes on Swift on the xcode 7.3.
We will adapt the code soon to those changes.

**Comment by gojkokbc** [comment]
Thank you very much.

**Comment by javiergonzper** [comment]
You are welcom :wink:

**Comment by gojkokbc** [comment]
Hi, I'm currently working with Xcode 7.2, and it works great, but i cannot test it with newer iOS version. Did you fix problems on Xcode 7.3?

**Comment by javiergonzper** [comment]
@gojkokbc check the "master" branch. It is fixed there. Will be in "stable" once we release it on the App Store

**Comment by gojkokbc** [comment]
Ok, thank you very much.

**Comment by javiergonzper** [comment]
You are welcome :wink:
